package view;

import view.SelectLevel;

/**
 *
 * @author Estiven Álvarez
 * @author Priscila Castro
 * @author Maikol Lizano
 *
 * @version 05 diciembre, 2018
 */
public class Instructions extends javax.swing.JDialog {

    /**
     * Creates new form Instructions
     */
    public Instructions(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbInstructions = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        btNext = new javax.swing.JButton();
        lbRule1 = new javax.swing.JLabel();
        lbRule2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbRule31 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbRule = new javax.swing.JLabel();
        lbRule51 = new javax.swing.JLabel();
        lbRule6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbInstructions.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        lbInstructions.setText("Instrucciones: ");

        btBack.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        btBack.setText("Regresar");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btNext.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        btNext.setText("Siguiente");
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }
        });

        lbRule1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lbRule1.setText("1- En el presente juego podrá elegir entre 4 niveles de dificultad.");

        lbRule2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lbRule2.setText("2- Se le presentarán las pistas para las palabras horizontales y  verticales respectivamente. ");
        lbRule2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel1.setText("3- Cuenta con 3 intentos, al exceder este límite, se le devolverá a la  ventana para volver a ");

        lbRule31.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lbRule31.setText("elegir un nivel.");

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel2.setText("4- Dependiendo del nivel que elija, se le presentará un tipo de ayuda  según la dificultad. ");

        lbRule.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lbRule.setText("5- Debe ser cuidadoso y completar todos los espacios solicitados,  de lo contrario  ");

        lbRule51.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lbRule51.setText("se descontará un intento.");

        lbRule6.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        lbRule6.setText("6- Puede optar por el botón de ayuda cuando sea posible, sin embargo, puede exceder el uso de este.  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNext))
                    .addComponent(lbInstructions)
                    .addComponent(lbRule1)
                    .addComponent(lbRule2)
                    .addComponent(jLabel1)
                    .addComponent(lbRule31)
                    .addComponent(jLabel2)
                    .addComponent(lbRule)
                    .addComponent(lbRule51)
                    .addComponent(lbRule6)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInstructions)
                .addGap(18, 18, 18)
                .addComponent(lbRule1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbRule2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbRule31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbRule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbRule51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbRule6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBack)
                    .addComponent(btNext))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        dispose();
    }//GEN-LAST:event_btBackActionPerformed

    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextActionPerformed
        SelectLevel selev = new SelectLevel(this, true);
        selev.setVisible(true);
    }//GEN-LAST:event_btNextActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbInstructions;
    private javax.swing.JLabel lbRule;
    private javax.swing.JLabel lbRule1;
    private javax.swing.JLabel lbRule2;
    private javax.swing.JLabel lbRule31;
    private javax.swing.JLabel lbRule51;
    private javax.swing.JLabel lbRule6;
    // End of variables declaration//GEN-END:variables
}
